In [1]:
import tensorflow as tf
import tensorflow.keras.backend as K

from tensorflow import keras
from tensorflow.keras.layers import Dense, Permute

In [2]:
print(tf.__version__)
print()
print(tf.constant(42))

2.9.0
tf.Tensor(42, shape=(), dtype=int32)
Metal device set to: Apple M1

systemMemory: 16.00 GB
maxCacheSize: 5.33 GB



2023-01-29 22:22:17.607538: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2023-01-29 22:22:17.607621: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [3]:
hidden_state = [[1, 2, 3, 4, 5] for _ in range(6)]
cell_state = [[6, 7, 8, 9, 10] for _ in range(6)]

test = tf.concat([hidden_state, cell_state], axis=-1)
print(test.shape)

(6, 10)


In [4]:
n = 3

hs = K.repeat(tf.concat([hidden_state, cell_state], axis=-1), n)
print(hs.shape)

(6, 3, 10)


In [5]:
T = 6

print(Dense(T)(hs).shape)

(6, 3, 6)


In [7]:
X = tf.constant([[[1, 2, 3, 4], [3, 4, 5, 6], [5, 6, 7, 8]], 
                 [[11, 22, 33, 44], [33, 44, 55, 66], [55, 66, 77, 88]]])

print(X)
print(X.shape)
print()

X_tr = Permute((2, 1))(X)
print(X_tr)
print(X_tr.shape)

tf.Tensor(
[[[ 1  2  3  4]
  [ 3  4  5  6]
  [ 5  6  7  8]]

 [[11 22 33 44]
  [33 44 55 66]
  [55 66 77 88]]], shape=(2, 3, 4), dtype=int32)
(2, 3, 4)

tf.Tensor(
[[[ 1  3  5]
  [ 2  4  6]
  [ 3  5  7]
  [ 4  6  8]]

 [[11 33 55]
  [22 44 66]
  [33 55 77]
  [44 66 88]]], shape=(2, 4, 3), dtype=int32)
(2, 4, 3)
